services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://database.intao.app:6379
      - ENVIRONMENT=PROD
      - TEAMS_GIT_CHANEL=${TEAMS_GIT_CHANEL}
      - DB_USER=unfbrbzgfgscg
      - DB_PASSWORD=meut1tbd0twk
      - DB_HOST=gfram1000.siteground.biz
      - DB_NAME=dblbufwzxkgog9
    volumes:
      - ./api:/app/api:delegated
      - ./requirements.txt:/app/requirements.txt:delegated
    networks:
      - intao-network
    depends_on:
      - services-manager

  services-manager:
    build:
      context: .
      dockerfile: routines/Dockerfile
    environment:
      - ENVIRONMENT=PROD
      - DB_USER=unfbrbzgfgscg
      - DB_PASSWORD=meut1tbd0twk
      - DB_HOST=gfram1000.siteground.biz
      - DB_NAME=dblbufwzxkgog9
    volumes:
      - ./routines:/app/routines:delegated
      - ./requirements.txt:/app/requirements.txt:delegated
    networks:
      - intao-network
    restart: unless-stopped

networks:
  intao-network:
    driver: bridge 